package by.epam.project.dao.query;

/**
 * Enumeration of query formator according to its entity.
 * @author Helena.Grouk
 */
public enum QueryType {
    CITYQUERY, COUNTRYQUERY, DESCRIPTIONQUERY, DIRECTIONCITYQUERY,
    DIRECTIONCOUNTRYQUERY, DIRECTIONQUERY, DIRECTIONSTAYHOTELQUERY,
    HOTELQUERY, ORDERQUERY, ROLEQUERY, SEARCHQUERY, TOURQUERY, TOURTYPEQUERY,
    TOURISTQUERY, TRANSMODEQUERY, USERQUERY
}
